# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."terraria-docker" = {
    image = "ryshe/terraria:vanilla-latest";
    environment = {
      "WORLD_FILENAME" = "Slimeworld.wld";
    };
    volumes = [
      "/etc/nixos/vanilla-data:/root/.local/share/Terraria/Worlds:rw"
    ];
    ports = [
      "7777:7777/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=terraria-docker"
      "--network=terraria_default"
    ];
  };
  systemd.services."podman-terraria-docker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-terraria_default.service"
    ];
    requires = [
      "podman-network-terraria_default.service"
    ];
    partOf = [
      "podman-compose-terraria-root.target"
    ];
    wantedBy = [
      "podman-compose-terraria-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-terraria_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f terraria_default";
    };
    script = ''
      podman network inspect terraria_default || podman network create terraria_default
    '';
    partOf = [ "podman-compose-terraria-root.target" ];
    wantedBy = [ "podman-compose-terraria-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-terraria-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
